### ISSUE TITLE
Secret Key is exposed in error thrown by this module

### ISSUE THREAD

**Issue by fedoseiev** [gettilled/tilled-node#18]
Can you please not expose sensitive data in your Errors... Logs are written in a lot of places and being worried that they can contain secret keys is a terrible situation 😢 

![image](https://github.com/gettilled/tilled-node/assets/32398977/5da69a4f-c1fa-4c56-9ae1-a25ec2e8cd25)

A bit off-topic:
Does your backend have `Cloudflare` enabled? I'm getting this HTML that my server was blocked... even though it is the first time it has been used 🙃

**Comment by dpatton1992** [comment]
Sorry for the delay here. I'm waiting on a review [here](https://github.com/gettilled/tilled-node/pull/20), and hope to get this merged in today. I als added a workflow to push these notifications to our slack feed to speed up resolution time going forward.

**Comment by dpatton1992** [comment]
Hey @fedoseiev, I just wanted to let you know we have patched this issue in #20. We stripped responses of the secret key, however, we left the account id since that is not secret. Please pull down our latest npm package (0.0.16)
